# Generated by Django 5.2.8 on 2026-08-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
